name: Publish Default Plugins

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 9.0.x

      - name: Update Plugins To Production Version
        run: |
             $version = "1.0.0"
             Get-Content appveyor.yml | ForEach-Object {
                 if ($_ -match "version:\s*'(\d+\.\d+\.\d+)\.") {
                     $version = $matches[1]
                 }
             }

             $jsonFiles = Get-ChildItem -Path ".\Plugins\*\plugin.json"
             foreach ($file in $jsonFiles) {
                 $plugin_old_ver = Get-Content $file.FullName -Raw | ConvertFrom-Json
                 (Get-Content $file) -replace '"Version"\s*:\s*".*?"', "`"Version`": `"$version`"" | Set-Content $file
                 $plugin_new_ver = Get-Content $file.FullName -Raw | ConvertFrom-Json
                 Write-Host "Updated" $plugin_old_ver.Name "version from" $plugin_old_ver.Version "to" $plugin_new_ver.Version
             }

      - name: Get BrowserBookmark Version
        id: updated-version-browserbookmark
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build BrowserBookmark
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish BrowserBookmark
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-browserbookmark.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get Calculator Version
        id: updated-version-calculator
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build Calculator
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish Calculator
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-calculator.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get Explorer Version
        id: updated-version-explorer
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build Explorer
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish Explorer
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-explorer.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get PluginIndicator Version
        id: updated-version-pluginindicator
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build PluginIndicator
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish PluginIndicator
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-pluginindicator.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get PluginsManager Version
        id: updated-version-pluginsmanager
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build PluginsManager
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish PluginsManager
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-pluginsmanager.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get ProcessKiller Version
        id: updated-version-processkiller
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build ProcessKiller
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish ProcessKiller
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-processkiller.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get Program Version
        id: updated-version-program
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build Program
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows10.0.19041.0  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish Program
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-program.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get Shell Version
        id: updated-version-shell
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build Shell
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish Shell
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-shell.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get Sys Version
        id: updated-version-sys
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build Sys
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish Sys
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-sys.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get Url Version
        id: updated-version-url
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build Url
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish Url
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-url.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get WebSearch Version
        id: updated-version-websearch
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build WebSearch
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish WebSearch
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-websearch.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}


      - name: Get WindowsSettings Version
        id: updated-version-windowssettings
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'Plugins/Creta.Plugin.BrowserBookmark/plugin.json'
          prop_path: 'Version'

      - name: Build WindowsSettings
        run: |
          dotnet publish 'Plugins/Creta.Plugin.BrowserBookmark/Creta.Plugin.BrowserBookmark.csproj' --framework net9.0-windows  -c Release -o "Creta.Plugin.BrowserBookmark"
          7z a -tzip "Creta.Plugin.BrowserBookmark.zip" "./Creta.Plugin.BrowserBookmark/*"
          rm -r "Creta.Plugin.BrowserBookmark"

      - name: Publish WindowsSettings
        uses: softprops/action-gh-release@v3
        with:
          repository: "Creta/Creta.Plugin.BrowserBookmark"
          files: "Creta.Plugin.BrowserBookmark.zip"
          tag_name: "v${{steps.updated-version-windowssettings.outputs.prop}}"
          body: Visit Flow's [release notes](https://github.com/Songchangan7/creta/releases) for changes.
          token: ${{ secrets.PUBLISH_PLUGINS }}
